window.LESSON_MAP = [
  {id:1,slug:'01-conceptos-clave',phase:'Fundamentos',title:'Conceptos clave de virtualización',summary:'Host, hipervisor, máquinas virtuales, VHDX y conmutadores.',source:'conceptos'},
  {id:2,slug:'02-requisitos-del-host',phase:'Fundamentos',title:'Requisitos del equipo anfitrión',summary:'Hardware, edición de Windows y capacidad necesaria.',source:'requisitos'},
  {id:3,slug:'03-descargas-oficiales',phase:'Fundamentos',title:'Descargas oficiales',summary:'ISO de Windows Server 2022 y verificación de archivos.',source:'descarga'},
  {id:4,slug:'04-instalar-hyper-v',phase:'Virtualización',title:'Instalar Hyper-V',summary:'Activación gráfica y mediante PowerShell.',source:'hyperv'},
  {id:5,slug:'05-red-virtual',phase:'Virtualización',title:'Configurar la red virtual',summary:'Conmutadores externos, internos y privados.',source:'red-virtual'},
  {id:6,slug:'06-crear-maquina-virtual',phase:'Virtualización',title:'Crear la máquina virtual',summary:'Generación, memoria, CPU, disco, ISO y red.',source:'maquina-virtual'},
  {id:7,slug:'07-instalar-server-2022',phase:'Despliegue',title:'Instalar Windows Server 2022',summary:'Edición Desktop Experience, particiones y primer arranque.',source:'server-2022'},
  {id:8,slug:'08-configuracion-inicial',phase:'Despliegue',title:'Configuración inicial del servidor',summary:'Nombre, zona horaria, IP fija, gateway y DNS.',source:'configuracion'},
  {id:9,slug:'09-acceso-administrador',phase:'Operación inicial',title:'Acceso del Administrador y controles de Hyper-V',summary:'Primer inicio, sesión mejorada y acciones de VMConnect.',course:5},
  {id:10,slug:'10-eventos-apagado',phase:'Operación inicial',title:'Seguimiento de eventos de apagado',summary:'Reinicios planeados, causas y registro de auditoría.',course:6},
  {id:11,slug:'11-primeras-actualizaciones',phase:'Actualizaciones',title:'Primer ciclo de actualizaciones',summary:'Conectividad externa, descarga e instalación segura.',course:7},
  {id:12,slug:'12-administrar-actualizaciones',phase:'Actualizaciones',title:'Administrar reinicios e historial',summary:'Ventanas, horas activas, historial y reversión.',course:8},
  {id:13,slug:'13-politicas-actualizacion',phase:'Actualizaciones',title:'Política local de actualizaciones',summary:'Directivas, opción 4 y programación del mantenimiento.',course:9},
  {id:14,slug:'14-usuarios-grupos',phase:'Identidades',title:'Usuarios y grupos locales',summary:'Cuentas, grupos funcionales y asignación de miembros.',course:10},
  {id:15,slug:'15-usuario-estandar',phase:'Identidades',title:'Acceso con usuario estándar',summary:'Primer acceso, UAC y principio de mínimo privilegio.',course:11},
  {id:16,slug:'16-server-manager',phase:'Administración',title:'Primer recorrido por Server Manager',summary:'Panel, servidor local, herramientas y alertas.',course:12},
  {id:17,slug:'17-nombre-servidor',phase:'Administración',title:'Cambiar el nombre del servidor',summary:'Convenciones, compatibilidad y reinicio.',course:13},
  {id:18,slug:'18-fecha-hora-region',phase:'Administración',title:'Fecha, hora, zona y región',summary:'Zona horaria, sincronización NTP y formatos.',course:14},
  {id:19,slug:'19-escritorio-remoto',phase:'Administración',title:'Escritorio remoto seguro',summary:'RDP, NLA, usuarios autorizados y firewall.',course:15},
  {id:20,slug:'20-microsoft-defender',phase:'Seguridad',title:'Microsoft Defender Antivirus',summary:'Protección, análisis, firmas y exclusiones.',course:16},
  {id:21,slug:'21-firewall-perfiles',phase:'Seguridad',title:'Perfiles y consola de Firewall',summary:'Dominio, privado, público y reglas avanzadas.',course:17},
  {id:22,slug:'22-regla-entrada',phase:'Seguridad',title:'Crear una regla de entrada',summary:'TCP, puerto local, perfiles, alcance y comprobación.',course:18},
  {id:23,slug:'23-reglas-salida',phase:'Seguridad',title:'Crear reglas de salida',summary:'Bloqueo por puerto y por programa.',course:19},
  {id:24,slug:'24-administrar-servicios',phase:'Operación',title:'Administración de servicios',summary:'Inicio, cuentas, recuperación y dependencias.',course:20},
  {id:25,slug:'25-active-directory',phase:'Módulo especial · Active Directory',title:'Implementar Active Directory Domain Services',summary:'Controlador de dominio, DNS, usuarios, grupos, GPO y unión de dos clientes.',source:'active-directory-module',featured:true},
  {id:26,slug:'25-validacion-laboratorio',phase:'Cierre',title:'Validar el laboratorio',summary:'Pruebas de host, VM, red, DNS y HTTPS.',source:'validacion'},
  {id:27,slug:'26-solucion-problemas',phase:'Cierre',title:'Solución de problemas frecuentes',summary:'Diagnóstico de Hyper-V, red, arranque y rendimiento.',source:'problemas'},
  {id:28,slug:'27-automatizacion-powershell',phase:'Cierre',title:'Automatización con PowerShell',summary:'Creación reproducible de la máquina virtual.',source:'automatizacion'},
  {id:29,slug:'28-evidencias-buenas-practicas',phase:'Cierre',title:'Evidencias y buenas prácticas',summary:'Checklist, documentación, seguridad y glosario.',source:'evidencias'}
];
window.lessonHref = (lesson) => `lecciones/${lesson.slug}.html`;
